services:
  mysql:
    container_name: mysql-container
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: onlineshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3357:3306"